#!/usr/bin/env tsx
/**
 * Synthesize Note Links
 * 
 * Applies deterministic link synthesis to imported notes:
 * 
 * LAYER 1 - Deterministic (modifies note files):
 *   - Convert entity ID patterns to structured mentions
 *   - Convert [[wikilinks]] to structured mentions
 * 
 * LAYER 2 - Heuristic (creates edge data):
 *   - Extract @mentions from text
 *   - Create "related" edges for topic overlaps
 *   - Create "references" edges for title mentions
 * 
 * Output:
 *   - Updated .note files with structured mentions
 *   - _synthesized_edges_.data file with discovered relationships
 */

import { homedir } from 'os'
import { join } from 'path'
import { readdir, readFile, writeFile, mkdir } from 'fs/promises'

const VAULT_PATH = join(homedir(), '.filegraph')
const NOTES_DIR = join(VAULT_PATH, '@notes')
const LOGS_DIR = join(VAULT_PATH, '.filegraph', 'logs')

// Run in dry-run mode by default
const DRY_RUN = process.argv.includes('--apply') ? false : true

interface NoteData {
  path: string
  filename: string
  id: string
  title: string
  status: string
  rawData: any
  fullText: string
  headings: string[]
}

interface SynthesizedEdge {
  source: string
  target: string
  type: 'mentions' | 'references' | 'related' | 'wikilink'
  confidence: 'high' | 'medium' | 'low'
  context?: string
  autoGenerated: true
  createdAt: string
}

interface SynthesisStats {
  notesProcessed: number
  notesModified: number
  entityMentionsAdded: number
  wikilinksConverted: number
  atMentionsExtracted: number
  relatedEdgesCreated: number
  referenceEdgesCreated: number
}

const stats: SynthesisStats = {
  notesProcessed: 0,
  notesModified: 0,
  entityMentionsAdded: 0,
  wikilinksConverted: 0,
  atMentionsExtracted: 0,
  relatedEdgesCreated: 0,
  referenceEdgesCreated: 0,
}

const synthesizedEdges: SynthesizedEdge[] = []
const modifiedNotes: Map<string, any> = new Map()

// ═══════════════════════════════════════════════════════════════════════════
// UTILITIES
// ═══════════════════════════════════════════════════════════════════════════

async function readNoteFile(filePath: string): Promise<any> {
  try {
    const content = await readFile(filePath, 'utf-8')
    return JSON.parse(content)
  } catch {
    return null
  }
}

async function getAllNotes(): Promise<NoteData[]> {
  const results: NoteData[] = []
  
  try {
    const entries = await readdir(NOTES_DIR, { withFileTypes: true })
    
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith('.note')) continue
      if (entry.name.startsWith('.') || entry.name.startsWith('_')) continue
      
      const fullPath = join(NOTES_DIR, entry.name)
      const data = await readNoteFile(fullPath)
      if (!data) continue
      
      // Extract full text and headings
      let fullText = ''
      const headings: string[] = []
      
      function extractText(blocks: any[]) {
        for (const block of blocks || []) {
          if (block.type === 'heading') {
            const text = (block.content || []).map((c: any) => c.text || '').join('')
            headings.push(text)
          }
          for (const content of block.content || []) {
            if (content.type === 'text') {
              fullText += ' ' + content.text
            }
          }
          if (block.children) extractText(block.children)
        }
      }
      
      extractText(data.blocks || [])
      
      results.push({
        path: fullPath,
        filename: entry.name,
        id: data['@id'] || data.id || `note:${entry.name.replace('.note', '')}`,
        title: data.title || entry.name.replace('.note', ''),
        status: data.status || 'unknown',
        rawData: data,
        fullText: fullText.toLowerCase(),
        headings,
      })
    }
  } catch (err) {
    console.error('Error loading notes:', err)
  }
  
  return results
}

function extractTextFromContent(content: any[]): string {
  return (content || []).map((c: any) => c.text || '').join('')
}

// ═══════════════════════════════════════════════════════════════════════════
// LAYER 1: ENTITY ID PATTERN CONVERSION
// ═══════════════════════════════════════════════════════════════════════════

function convertEntityPatterns(note: NoteData): number {
  let conversions = 0
  const entityPattern = /\b(person|proj|org|task|ms|acc|bill|event|goal|note):[a-z0-9_-]+(?::[0-9]+)?\b/gi
  
  function processBlocks(blocks: any[]): any[] {
    return blocks.map(block => {
      const newBlock = { ...block }
      
      if (block.content) {
        const newContent: any[] = []
        
        for (const item of block.content) {
          if (item.type === 'text' && item.text) {
            // Split text by entity patterns
            const parts = item.text.split(entityPattern)
            const matches = item.text.match(entityPattern) || []
            
            let matchIndex = 0
            for (let i = 0; i < parts.length; i++) {
              if (parts[i]) {
                newContent.push({ type: 'text', text: parts[i] })
              }
              if (matchIndex < matches.length) {
                newContent.push({
                  type: 'mention',
                  entityId: matches[matchIndex].toLowerCase(),
                  autoGenerated: true,
                })
                conversions++
                matchIndex++
              }
            }
          } else {
            newContent.push(item)
          }
        }
        
        newBlock.content = newContent
      }
      
      if (block.children) {
        newBlock.children = processBlocks(block.children)
      }
      
      return newBlock
    })
  }
  
  if (note.rawData.blocks) {
    note.rawData.blocks = processBlocks(note.rawData.blocks)
  }
  
  return conversions
}

// ═══════════════════════════════════════════════════════════════════════════
// LAYER 1: WIKILINK CONVERSION [[note title]]
// ═══════════════════════════════════════════════════════════════════════════

function convertWikilinks(note: NoteData, titleToId: Map<string, string>): number {
  let conversions = 0
  const wikilinkPattern = /\[\[([^\]]+)\]\]/g
  
  function processBlocks(blocks: any[]): any[] {
    return blocks.map(block => {
      const newBlock = { ...block }
      
      if (block.content) {
        const newContent: any[] = []
        
        for (const item of block.content) {
          if (item.type === 'text' && item.text) {
            let text = item.text
            let lastIndex = 0
            let match
            
            wikilinkPattern.lastIndex = 0
            while ((match = wikilinkPattern.exec(text)) !== null) {
              // Add text before the match
              if (match.index > lastIndex) {
                newContent.push({ type: 'text', text: text.slice(lastIndex, match.index) })
              }
              
              const linkTitle = match[1].trim()
              const targetId = titleToId.get(linkTitle.toLowerCase())
              
              if (targetId) {
                newContent.push({
                  type: 'mention',
                  entityId: targetId,
                  displayText: linkTitle,
                  autoGenerated: true,
                })
                conversions++
              } else {
                // Keep as wikilink text if no matching note found
                newContent.push({
                  type: 'wikilink',
                  target: linkTitle,
                  autoGenerated: true,
                })
              }
              
              lastIndex = match.index + match[0].length
            }
            
            // Add remaining text
            if (lastIndex < text.length) {
              newContent.push({ type: 'text', text: text.slice(lastIndex) })
            }
            
            if (lastIndex === 0) {
              // No wikilinks found, keep original
              newContent.push(item)
            }
          } else {
            newContent.push(item)
          }
        }
        
        newBlock.content = newContent
      }
      
      if (block.children) {
        newBlock.children = processBlocks(block.children)
      }
      
      return newBlock
    })
  }
  
  if (note.rawData.blocks) {
    note.rawData.blocks = processBlocks(note.rawData.blocks)
  }
  
  return conversions
}

// ═══════════════════════════════════════════════════════════════════════════
// LAYER 2: @MENTION EXTRACTION
// ═══════════════════════════════════════════════════════════════════════════

function extractAtMentions(note: NoteData): string[] {
  const mentions: string[] = []
  // Pattern: @word or @word:subword
  const atPattern = /@([a-zA-Z][a-zA-Z0-9_-]*(?::[a-zA-Z0-9_-]+)?)/g
  
  let match
  while ((match = atPattern.exec(note.fullText)) !== null) {
    const mention = match[1].toLowerCase()
    // Filter out common false positives
    if (!['media', 'import', 'keyframes', 'font-face', 'charset', 'supports', 'layer', 'scope'].includes(mention)) {
      if (!mentions.includes(mention)) {
        mentions.push(mention)
      }
    }
  }
  
  return mentions
}

// ═══════════════════════════════════════════════════════════════════════════
// LAYER 2: TITLE REFERENCE EDGES
// ═══════════════════════════════════════════════════════════════════════════

function findTitleReferences(notes: NoteData[]): void {
  const titleMap = new Map<string, NoteData>()
  
  for (const note of notes) {
    const normalized = note.title.toLowerCase().trim()
    if (normalized.length > 5) {
      titleMap.set(normalized, note)
    }
  }
  
  for (const sourceNote of notes) {
    for (const [title, targetNote] of titleMap) {
      if (sourceNote.id === targetNote.id) continue
      if (title.length < 8) continue // Stricter for edge creation
      
      if (sourceNote.fullText.includes(title)) {
        const idx = sourceNote.fullText.indexOf(title)
        const context = sourceNote.fullText.slice(Math.max(0, idx - 40), idx + title.length + 40).trim()
        
        synthesizedEdges.push({
          source: sourceNote.id,
          target: targetNote.id,
          type: 'references',
          confidence: title.length > 15 ? 'high' : 'medium',
          context: context.slice(0, 100),
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        })
        stats.referenceEdgesCreated++
      }
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// LAYER 2: TOPIC OVERLAP EDGES
// ═══════════════════════════════════════════════════════════════════════════

function findTopicOverlaps(notes: NoteData[]): void {
  const stopWords = new Set([
    'the', 'and', 'for', 'with', 'from', 'that', 'this', 'what', 'how', 'why',
    'when', 'where', 'who', 'which', 'your', 'our', 'their', 'about', 'into',
    'through', 'during', 'before', 'after', 'above', 'below', 'between', 'under',
    'over', 'out', 'off', 'down', 'away', 'more', 'most', 'other', 'some', 'such',
    'only', 'same', 'than', 'too', 'very', 'just', 'also', 'back', 'been', 'being',
    'both', 'but', 'can', 'did', 'does', 'doing', 'done', 'each', 'few', 'get',
    'would', 'could', 'should', 'will', 'using', 'based', 'like', 'make', 'made',
    'need', 'want', 'work', 'take', 'give', 'think', 'know', 'see', 'come', 'look',
  ])
  
  const noteKeywords = new Map<NoteData, Set<string>>()
  
  for (const note of notes) {
    const keywords = new Set<string>()
    
    // Extract from headings (higher weight)
    for (const heading of note.headings) {
      const words = heading.toLowerCase()
        .replace(/[^a-z0-9\s]/g, '')
        .split(/\s+/)
        .filter(w => w.length > 4 && !stopWords.has(w))
      words.forEach(w => keywords.add(w))
    }
    
    // Extract from title
    const titleWords = note.title.toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(/\s+/)
      .filter(w => w.length > 4 && !stopWords.has(w))
    titleWords.forEach(w => keywords.add(w))
    
    noteKeywords.set(note, keywords)
  }
  
  const checked = new Set<string>()
  
  for (const [note1, keywords1] of noteKeywords) {
    for (const [note2, keywords2] of noteKeywords) {
      if (note1.id === note2.id) continue
      
      const pairKey = [note1.id, note2.id].sort().join('|')
      if (checked.has(pairKey)) continue
      checked.add(pairKey)
      
      const overlap = [...keywords1].filter(k => keywords2.has(k))
      
      // Only high confidence (5+ shared keywords)
      if (overlap.length >= 5) {
        synthesizedEdges.push({
          source: note1.id,
          target: note2.id,
          type: 'related',
          confidence: overlap.length >= 7 ? 'high' : 'medium',
          context: `Shared topics: ${overlap.slice(0, 8).join(', ')}`,
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        })
        stats.relatedEdgesCreated++
      }
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════

async function main() {
  console.log('🔗 Synthesize Note Links\n')
  console.log(`Vault: ${VAULT_PATH}`)
  console.log(`Mode: ${DRY_RUN ? '🔍 DRY RUN (use --apply to write changes)' : '✏️  APPLYING CHANGES'}\n`)
  
  await mkdir(LOGS_DIR, { recursive: true })
  
  // Load all notes
  console.log('Loading notes...')
  const notes = await getAllNotes()
  console.log(`✓ Loaded ${notes.length} notes\n`)
  stats.notesProcessed = notes.length
  
  // Build title → id map for wikilink resolution
  const titleToId = new Map<string, string>()
  for (const note of notes) {
    titleToId.set(note.title.toLowerCase(), note.id)
  }
  
  // ─────────────────────────────────────────────────────────────────────────
  // LAYER 1: Modify note files
  // ─────────────────────────────────────────────────────────────────────────
  
  console.log('═'.repeat(80))
  console.log('LAYER 1: Converting inline patterns to structured mentions')
  console.log('─'.repeat(80))
  
  for (const note of notes) {
    let modified = false
    
    // Convert entity ID patterns
    const entityConversions = convertEntityPatterns(note)
    if (entityConversions > 0) {
      stats.entityMentionsAdded += entityConversions
      modified = true
    }
    
    // Convert wikilinks
    const wikilinkConversions = convertWikilinks(note, titleToId)
    if (wikilinkConversions > 0) {
      stats.wikilinksConverted += wikilinkConversions
      modified = true
    }
    
    if (modified) {
      stats.notesModified++
      modifiedNotes.set(note.path, note.rawData)
      
      if (!DRY_RUN) {
        console.log(`  ✏️  ${note.filename}: ${entityConversions} entities, ${wikilinkConversions} wikilinks`)
      }
    }
  }
  
  console.log(`\n✓ Entity patterns converted: ${stats.entityMentionsAdded}`)
  console.log(`✓ Wikilinks converted: ${stats.wikilinksConverted}`)
  console.log(`✓ Notes to modify: ${stats.notesModified}`)
  
  // ─────────────────────────────────────────────────────────────────────────
  // LAYER 2: Create edge data
  // ─────────────────────────────────────────────────────────────────────────
  
  console.log('\n' + '═'.repeat(80))
  console.log('LAYER 2: Creating relationship edges')
  console.log('─'.repeat(80))
  
  // Extract @mentions
  console.log('\nExtracting @mentions...')
  const allAtMentions = new Set<string>()
  for (const note of notes) {
    const mentions = extractAtMentions(note)
    mentions.forEach(m => allAtMentions.add(m))
    stats.atMentionsExtracted += mentions.length
  }
  console.log(`✓ Found ${allAtMentions.size} unique @mentions: ${[...allAtMentions].slice(0, 10).join(', ')}${allAtMentions.size > 10 ? '...' : ''}`)
  
  // Find title references
  console.log('\nFinding title references...')
  findTitleReferences(notes)
  console.log(`✓ Created ${stats.referenceEdgesCreated} reference edges`)
  
  // Find topic overlaps
  console.log('\nFinding topic overlaps...')
  findTopicOverlaps(notes)
  console.log(`✓ Created ${stats.relatedEdgesCreated} related edges`)
  
  // ─────────────────────────────────────────────────────────────────────────
  // Write results
  // ─────────────────────────────────────────────────────────────────────────
  
  console.log('\n' + '═'.repeat(80))
  console.log('RESULTS')
  console.log('─'.repeat(80))
  
  if (DRY_RUN) {
    console.log('\n🔍 DRY RUN - No files modified')
    console.log('\nWould modify these notes:')
    let count = 0
    for (const [path] of modifiedNotes) {
      if (count < 10) console.log(`  - ${path.replace(VAULT_PATH, '~')}`)
      count++
    }
    if (count > 10) console.log(`  ... and ${count - 10} more`)
    
    console.log('\nTo apply changes, run:')
    console.log('  npx tsx scripts/synthesize-note-links.ts --apply')
  } else {
    // Write modified notes
    console.log('\nWriting modified notes...')
    for (const [path, data] of modifiedNotes) {
      await writeFile(path, JSON.stringify(data, null, 2))
    }
    console.log(`✓ Updated ${modifiedNotes.size} note files`)
    
    // Write synthesized edges
    const edgesFile = join(NOTES_DIR, '_synthesized_edges_.data')
    const edgesData = {
      '@context': { 'schema': 'https://schema.org/' },
      '@type': 'SynthesizedEdgeCollection',
      '@id': 'edges:synthesized',
      'description': 'Auto-generated relationship edges from note content analysis',
      'generatedAt': new Date().toISOString(),
      'stats': {
        referenceEdges: stats.referenceEdgesCreated,
        relatedEdges: stats.relatedEdgesCreated,
        totalEdges: synthesizedEdges.length,
      },
      'items': synthesizedEdges,
    }
    await writeFile(edgesFile, JSON.stringify(edgesData, null, 2))
    console.log(`✓ Created ${edgesFile.replace(VAULT_PATH, '~')} with ${synthesizedEdges.length} edges`)
  }
  
  // Write log
  const logFile = join(LOGS_DIR, `synthesize-links-${new Date().toISOString().replace(/[:.]/g, '-')}.json`)
  const logData = {
    timestamp: new Date().toISOString(),
    dryRun: DRY_RUN,
    stats,
    sampleEdges: synthesizedEdges.slice(0, 50),
    modifiedNotes: [...modifiedNotes.keys()].map(p => p.replace(VAULT_PATH, '~')),
  }
  await writeFile(logFile, JSON.stringify(logData, null, 2))
  
  // Summary
  console.log('\n' + '═'.repeat(80))
  console.log('📊 SUMMARY')
  console.log('─'.repeat(80))
  console.log(`
Notes processed:        ${stats.notesProcessed}
Notes modified:         ${stats.notesModified}

LAYER 1 (inline):
  Entity mentions:      ${stats.entityMentionsAdded}
  Wikilinks converted:  ${stats.wikilinksConverted}

LAYER 2 (edges):
  Reference edges:      ${stats.referenceEdgesCreated}
  Related edges:        ${stats.relatedEdgesCreated}
  Total edges:          ${synthesizedEdges.length}

Log file: ${logFile.replace(VAULT_PATH, '~')}
`)

  // Show sample edges
  console.log('Sample synthesized edges:')
  synthesizedEdges.slice(0, 5).forEach(edge => {
    console.log(`  ${edge.source} --[${edge.type}]--> ${edge.target}`)
    if (edge.context) console.log(`    "${edge.context.slice(0, 60)}..."`)
  })
}

main().catch(console.error)
