#!/usr/bin/env tsx
/**
 * Edge Synthesis Orchestrator
 *
 * Coordinates all synthesis scripts and provides modular, incremental synthesis.
 *
 * This orchestrates:
 * 1. Entity edge synthesis (from .data files)
 * 2. Note link synthesis (from .note files)
 * 3. Organization synthesis (from project clients)
 * 4. People relationship synthesis
 *
 * Can run:
 * - Full synthesis (all entities)
 * - Incremental synthesis (only changed entities)
 * - Specific synthesis layers
 */

import { join } from 'path'
import { homedir } from 'os'
import { readFile, writeFile, readdir } from 'fs/promises'
import { existsSync } from 'fs'

// Paths
const VAULT_PATH = join(process.cwd(), 'src', 'data', 'demo-files')
const ENTITIES_PATH = join(VAULT_PATH, '@entities')
const NOTES_PATH = join(VAULT_PATH, '@notes')
const GRAPH_FILE = join(ENTITIES_PATH, '_graph_.data')

// CLI flags
const DRY_RUN = !process.argv.includes('--apply')
const INCREMENTAL_MODE = process.argv.includes('--incremental')
const CHANGED_FILES =
  process.argv
    .filter((arg) => arg.startsWith('--files='))[0]
    ?.replace('--files=', '')
    .split(',') || []

interface Edge {
  source: string
  target: string
  label: string
  metadata?: {
    confidence?: 'high' | 'medium' | 'low'
    context?: string
    autoGenerated?: boolean
    createdAt?: string
  }
}

interface Node {
  id: string
  type: string
  label: string
  file: string
}

interface GraphData {
  '@context': any
  '@id': string
  '@type': string
  namespace: string
  description: string
  nodes: Node[]
  edges: Edge[]
  stats?: {
    nodeCount?: any
    edgeCount?: any
    lastUpdated?: string
  }
}

// Stats tracking
const stats = {
  nodesAdded: 0,
  nodesUpdated: 0,
  edgesAdded: 0,
  edgesRemoved: 0,
  filesProcessed: 0,
  duration: 0,
}

// ═══════════════════════════════════════════════════════════════════════════
// UTILITIES
// ═══════════════════════════════════════════════════════════════════════════

async function loadDataFile<T = any>(filePath: string): Promise<T | null> {
  if (!existsSync(filePath)) return null
  try {
    const content = await readFile(filePath, 'utf-8')
    return JSON.parse(content)
  } catch (err) {
    console.error(`Failed to load ${filePath}:`, err)
    return null
  }
}

async function loadGraph(): Promise<GraphData> {
  const existing = await loadDataFile<GraphData>(GRAPH_FILE)

  if (existing) return existing

  // Initialize new graph
  return {
    '@context': { fg: 'https://filegraph.local/graph/' },
    '@id': 'fg:entities:graph',
    '@type': 'FederatedGraph',
    namespace: '@entities',
    description: 'Federated graph of all core entities in the vault',
    nodes: [],
    edges: [],
    stats: {
      nodeCount: { '@expr': 'nodes.length' },
      edgeCount: { '@expr': 'edges.length' },
      lastUpdated: new Date().toISOString(),
    },
  }
}

async function saveGraph(graph: GraphData) {
  graph.stats = {
    ...graph.stats,
    nodeCount: { '@expr': 'nodes.length' },
    edgeCount: { '@expr': 'edges.length' },
    lastUpdated: new Date().toISOString(),
  }

  await writeFile(GRAPH_FILE, JSON.stringify(graph, null, 2))
}

function createEdgeKey(edge: Edge): string {
  return `${edge.source}::${edge.label}::${edge.target}`
}

function log(message: string, level: 'info' | 'success' | 'warn' | 'error' = 'info') {
  const icons = { info: '•', success: '✓', warn: '⚠', error: '✗' }
  console.log(`${icons[level]} ${message}`)
}

// ═══════════════════════════════════════════════════════════════════════════
// SYNTHESIS LAYERS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Layer 1: Entity nodes (from .data files)
 */
async function synthesizeEntityNodes(graph: GraphData, files?: string[]): Promise<void> {
  log('Synthesizing entity nodes...')

  const entityFiles = files || (await readdir(ENTITIES_PATH)).filter((f) => f.endsWith('.data') && !f.startsWith('_'))

  const nodeMap = new Map(graph.nodes.map((n) => [n.id, n]))

  for (const filename of entityFiles) {
    const filePath = typeof filename === 'string' && filename.includes('/') ? filename : join(ENTITIES_PATH, filename)

    if (!existsSync(filePath)) continue

    const data = await loadDataFile<{ '@type'?: string; items?: any[] }>(filePath)
    if (!data || !data.items) continue

    const entityType = filename.replace('.data', '')

    for (const item of data.items) {
      if (!item.id) continue

      const node: Node = {
        id: item.id,
        type: data['@type'] || entityType,
        label: item.name || item.title || item.id,
        file: filename,
      }

      if (nodeMap.has(node.id)) {
        // Update existing node
        const existing = nodeMap.get(node.id)!
        existing.label = node.label
        existing.type = node.type
        stats.nodesUpdated++
      } else {
        // Add new node
        graph.nodes.push(node)
        nodeMap.set(node.id, node)
        stats.nodesAdded++
      }
    }

    stats.filesProcessed++
  }

  log(`  Added ${stats.nodesAdded} nodes, updated ${stats.nodesUpdated}`, 'success')
}

/**
 * Layer 2: Deterministic edges (from structured fields)
 */
async function synthesizeDeterministicEdges(graph: GraphData, files?: string[]): Promise<void> {
  log('Synthesizing deterministic edges...')

  const entityFiles = files || (await readdir(ENTITIES_PATH)).filter((f) => f.endsWith('.data') && !f.startsWith('_'))

  const edgeMap = new Map(graph.edges.map((e) => [createEdgeKey(e), e]))
  const newEdges: Edge[] = []

  for (const filename of entityFiles) {
    const filePath = typeof filename === 'string' && filename.includes('/') ? filename : join(ENTITIES_PATH, filename)

    if (!existsSync(filePath)) continue

    const data = await loadDataFile<{ items?: any[] }>(filePath)
    if (!data || !data.items) continue

    for (const item of data.items) {
      if (!item.id) continue

      // People edges
      if (filename === 'people.data') {
        if (item.organization) {
          newEdges.push({
            source: item.id,
            target: item.organization,
            label: 'works_at',
            metadata: {
              confidence: 'high',
              context: 'Organizational affiliation',
              autoGenerated: true,
              createdAt: new Date().toISOString(),
            },
          })
        }
      }

      // Project edges
      else if (filename === 'projects.data') {
        if (item.client) {
          newEdges.push({
            source: item.id,
            target: item.client,
            label: 'client',
            metadata: { confidence: 'high', autoGenerated: true },
          })
        }

        if (item.lead) {
          newEdges.push({
            source: item.id,
            target: item.lead,
            label: 'lead',
            metadata: { confidence: 'high', autoGenerated: true },
          })
        }

        if (Array.isArray(item.team)) {
          for (const member of item.team) {
            newEdges.push({
              source: item.id,
              target: member,
              label: 'team_member',
              metadata: { confidence: 'high', autoGenerated: true },
            })
          }
        }
      }

      // Task edges
      else if (filename === 'tasks.data') {
        if (item.project) {
          newEdges.push({
            source: item.id,
            target: item.project,
            label: 'project',
            metadata: { confidence: 'high', autoGenerated: true },
          })
        }

        if (item.assignee) {
          newEdges.push({
            source: item.id,
            target: item.assignee,
            label: 'assignee',
            metadata: { confidence: 'high', autoGenerated: true },
          })
        }

        if (item.milestone) {
          newEdges.push({
            source: item.id,
            target: item.milestone,
            label: 'milestone',
            metadata: { confidence: 'high', autoGenerated: true },
          })
        }
      }

      // Milestone edges
      else if (filename === 'milestones.data') {
        if (item.project) {
          newEdges.push({
            source: item.id,
            target: item.project,
            label: 'project',
            metadata: { confidence: 'high', autoGenerated: true },
          })
        }
      }
    }
  }

  // Add unique edges
  for (const edge of newEdges) {
    const key = createEdgeKey(edge)
    if (!edgeMap.has(key)) {
      graph.edges.push(edge)
      edgeMap.set(key, edge)
      stats.edgesAdded++
    }
  }

  log(`  Added ${stats.edgesAdded} deterministic edges`, 'success')
}

/**
 * Layer 3: Heuristic edges (from note content)
 */
async function synthesizeHeuristicEdges(graph: GraphData, files?: string[]): Promise<void> {
  log('Synthesizing heuristic edges...')

  const noteFiles =
    files?.filter((f) => f.endsWith('.note')) || (await readdir(NOTES_PATH)).filter((f) => f.endsWith('.note'))

  const edgeMap = new Map(graph.edges.map((e) => [createEdgeKey(e), e]))
  const entityIdPattern = /\b(person|org|proj|task|ms|event):[a-z0-9-]+:[0-9]+\b/g

  let heuristicEdges = 0

  for (const filename of noteFiles) {
    const filePath = typeof filename === 'string' && filename.includes('/') ? filename : join(NOTES_PATH, filename)

    if (!existsSync(filePath)) continue

    const note = await loadDataFile<{ '@id'?: string; blocks?: any[] }>(filePath)
    if (!note || !note['@id']) continue

    // Extract entity mentions
    const fullText = JSON.stringify(note.blocks || [])
    const matches = fullText.match(entityIdPattern) || []
    const uniqueMatches = [...new Set(matches)]

    for (const entityId of uniqueMatches) {
      const edge: Edge = {
        source: note['@id'],
        target: entityId,
        label: 'mentions',
        metadata: {
          confidence: 'medium',
          context: 'Entity mention in note content',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
      }

      const key = createEdgeKey(edge)
      if (!edgeMap.has(key)) {
        graph.edges.push(edge)
        edgeMap.set(key, edge)
        heuristicEdges++
      }
    }
  }

  log(`  Added ${heuristicEdges} heuristic edges`, 'success')
}

/**
 * Layer 4: Cleanup (remove stale edges)
 */
async function cleanupStaleEdges(graph: GraphData): Promise<void> {
  log('Cleaning up stale edges...')

  const validNodeIds = new Set(graph.nodes.map((n) => n.id))
  const initialCount = graph.edges.length

  graph.edges = graph.edges.filter((edge) => {
    return validNodeIds.has(edge.source) && validNodeIds.has(edge.target)
  })

  const removed = initialCount - graph.edges.length
  stats.edgesRemoved = removed

  if (removed > 0) {
    log(`  Removed ${removed} stale edges`, 'warn')
  } else {
    log(`  No stale edges found`, 'success')
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════

async function main() {
  const startTime = Date.now()

  console.log('🔗 Edge Synthesis Orchestrator\n')
  console.log(`Mode: ${DRY_RUN ? '🔍 DRY RUN' : '✏️  APPLYING'}`)
  console.log(`Incremental: ${INCREMENTAL_MODE ? 'YES' : 'NO'}`)
  if (CHANGED_FILES.length > 0) {
    console.log(`Files: ${CHANGED_FILES.length} specified\n`)
  } else {
    console.log('Files: ALL\n')
  }

  // Load graph
  const graph = await loadGraph()
  log(`Loaded graph: ${graph.nodes.length} nodes, ${graph.edges.length} edges\n`)

  // Run synthesis layers
  await synthesizeEntityNodes(graph, CHANGED_FILES.length > 0 ? CHANGED_FILES : undefined)
  await synthesizeDeterministicEdges(graph, CHANGED_FILES.length > 0 ? CHANGED_FILES : undefined)
  await synthesizeHeuristicEdges(graph, CHANGED_FILES.length > 0 ? CHANGED_FILES : undefined)
  await cleanupStaleEdges(graph)

  // Save graph
  if (!DRY_RUN) {
    await saveGraph(graph)
    log(`\n✅ Graph saved to ${GRAPH_FILE}`, 'success')
  } else {
    log(`\n📝 DRY RUN: Would save graph to ${GRAPH_FILE}`, 'info')
  }

  stats.duration = Date.now() - startTime

  // Print summary
  console.log('\n' + '═'.repeat(60))
  console.log('Summary:')
  console.log(`  Nodes: ${graph.nodes.length} total (${stats.nodesAdded} added, ${stats.nodesUpdated} updated)`)
  console.log(`  Edges: ${graph.edges.length} total (${stats.edgesAdded} added, ${stats.edgesRemoved} removed)`)
  console.log(`  Files processed: ${stats.filesProcessed}`)
  console.log(`  Duration: ${stats.duration}ms`)
  console.log('═'.repeat(60))

  if (DRY_RUN) {
    console.log('\n💡 To apply changes, run with --apply flag')
  }
}

main().catch((err) => {
  console.error('❌ Fatal error:', err)
  process.exit(1)
})
