/**
 * Default keyboard shortcuts
 */

import { KeyCategory, type KeybindingDefinition } from './types'

export const DEFAULT_KEYBINDINGS: KeybindingDefinition[] = [
  // === Navigation ===
  {
    id: 'navigate.back',
    category: KeyCategory.Navigation,
    key: 'cmd+left',
    default: 'cmd+left',
    command: 'navigation.back',
    description: 'Navigate backward in history',
    metadata: {
      action: 'Move to the previous directory in the navigation history stack of the active tab',
      domain: 'navigation',
      target: 'active_tab_history',
    },
    when: 'canNavigateBack && !editorFocus',
    priority: 100,
  },
  {
    id: 'navigate.forward',
    category: KeyCategory.Navigation,
    key: 'cmd+right',
    default: 'cmd+right',
    command: 'navigation.forward',
    description: 'Navigate forward in history',
    metadata: {
      action: 'Move to the next directory in the navigation history stack of the active tab',
      domain: 'navigation',
      target: 'active_tab_history',
    },
    when: 'canNavigateForward && !editorFocus',
    priority: 100,
  },
  {
    id: 'navigate.home',
    category: KeyCategory.Navigation,
    key: 'cmd+shift+h',
    default: 'cmd+shift+h',
    command: 'navigation.home',
    description: 'Navigate to home directory',
    metadata: {
      action: 'Navigate the active tab to the user home directory',
      domain: 'navigation',
      target: 'active_tab_path',
    },
  },
  {
    id: 'navigate.up',
    category: KeyCategory.Navigation,
    key: 'cmd+up',
    default: 'cmd+up',
    command: 'navigation.up',
    description: 'Navigate to parent directory',
    metadata: {
      action: 'Navigate the active tab to the parent directory of the current path',
      domain: 'navigation',
      target: 'active_tab_path',
    },
  },
  {
    id: 'navigate.refresh',
    category: KeyCategory.Navigation,
    key: 'cmd+r',
    default: 'cmd+r',
    command: 'navigation.refresh',
    description: 'Refresh current directory',
    metadata: {
      action: 'Reload the file list for the current directory in the active tab',
      domain: 'file_system',
      target: 'file_list',
    },
  },

  // === File Operations ===
  {
    id: 'file.new',
    category: KeyCategory.FileOperations,
    key: 'cmd+n',
    default: 'cmd+n',
    command: 'file.new',
    description: 'Create new file',
    metadata: {
      action: 'Create a new empty file in the current directory',
      domain: 'file_system',
      target: 'current_directory',
    },
  },
  {
    id: 'file.newFolder',
    category: KeyCategory.FileOperations,
    key: 'cmd+shift+n',
    default: 'cmd+shift+n',
    command: 'file.newFolder',
    description: 'Create new folder',
    metadata: {
      action: 'Create a new empty folder in the current directory',
      domain: 'file_system',
      target: 'current_directory',
    },
  },
  {
    id: 'file.delete',
    category: KeyCategory.FileOperations,
    key: 'cmd+backspace',
    default: 'cmd+backspace',
    command: 'file.delete',
    description: 'Move to trash (immediate)',
    when: 'hasSelection',
    metadata: {
      action: 'Move selected files or folders to trash immediately without confirmation',
      domain: 'file_system',
      target: 'selected_items',
    },
  },
  {
    id: 'file.deleteWithConfirmation',
    category: KeyCategory.FileOperations,
    key: 'backspace',
    default: 'backspace',
    command: 'file.deleteWithConfirmation',
    description: 'Move to trash (with confirmation)',
    when: 'hasSelection',
    metadata: {
      action: 'Show confirmation dialog before moving selected files or folders to trash',
      domain: 'file_system',
      target: 'selected_items',
    },
  },
  {
    id: 'file.rename',
    category: KeyCategory.FileOperations,
    key: 'enter',
    default: 'enter',
    command: 'file.rename',
    description: 'Rename selected file',
    when: 'hasSelection && !isEditing',
    metadata: {
      action: 'Enter rename mode for the currently selected file',
      domain: 'ui_state',
      target: 'selected_item_name',
    },
  },
  {
    id: 'file.cut',
    category: KeyCategory.FileOperations,
    key: 'cmd+x',
    default: 'cmd+x',
    command: 'file.cut',
    description: 'Cut selected file(s)',
    when: 'hasSelection && fileExplorerFocus',
    metadata: {
      action: 'Move selected files to clipboard and mark for move operation',
      domain: 'clipboard',
      target: 'system_clipboard',
    },
  },
  {
    id: 'file.copy',
    category: KeyCategory.FileOperations,
    key: 'cmd+c',
    default: 'cmd+c',
    command: 'file.copy',
    description: 'Copy selected file(s)',
    when: 'hasSelection && fileExplorerFocus',
    metadata: {
      action: 'Copy selected files to clipboard',
      domain: 'clipboard',
      target: 'system_clipboard',
    },
  },
  {
    id: 'file.paste',
    category: KeyCategory.FileOperations,
    key: 'cmd+v',
    default: 'cmd+v',
    command: 'file.paste',
    description: 'Paste file(s)',
    when: 'hasClipboard && fileExplorerFocus',
    metadata: {
      action: 'Paste files from clipboard into the current directory',
      domain: 'file_system',
      target: 'current_directory',
    },
  },

  // === View ===
  {
    id: 'view.togglePreview',
    category: KeyCategory.View,
    key: 'cmd+shift+p',
    default: 'cmd+shift+p',
    command: 'view.togglePreview',
    description: 'Toggle preview pane',
    metadata: {
      action: 'Show or hide the file preview pane',
      domain: 'ui_state',
      target: 'preview_pane_visibility',
    },
  },
  {
    id: 'view.layoutTree',
    category: KeyCategory.View,
    key: 'cmd+1',
    default: 'cmd+1',
    command: 'view.setLayout',
    args: { mode: 'tree' },
    description: 'Switch to tree layout',
    when: '!isFullscreenMode',
    metadata: {
      action: 'Change the file explorer view mode to Tree View',
      domain: 'ui_state',
      target: 'layout_mode',
    },
  },
  {
    id: 'view.layoutColumn',
    category: KeyCategory.View,
    key: 'cmd+2',
    default: 'cmd+2',
    command: 'view.setLayout',
    args: { mode: 'column' },
    description: 'Switch to column layout',
    when: '!isFullscreenMode',
    metadata: {
      action: 'Change the file explorer view mode to Column View',
      domain: 'ui_state',
      target: 'layout_mode',
    },
  },
  {
    id: 'view.layoutGrid',
    category: KeyCategory.View,
    key: 'cmd+3',
    default: 'cmd+3',
    command: 'view.setLayout',
    args: { mode: 'grid' },
    description: 'Switch to grid layout',
    when: '!isFullscreenMode',
    metadata: {
      action: 'Change the file explorer view mode to Grid View',
      domain: 'ui_state',
      target: 'layout_mode',
    },
  },
  {
    id: 'view.toggleDotfiles',
    category: KeyCategory.View,
    key: 'cmd+shift+.',
    default: 'cmd+shift+.',
    command: 'view.toggleDotfiles',
    description: 'Show/hide dotfiles',
    metadata: {
      action: 'Toggle visibility of hidden files (dotfiles)',
      domain: 'ui_state',
      target: 'file_filter',
    },
  },
  {
    id: 'view.zoomIn',
    category: KeyCategory.View,
    key: 'cmd+=',
    default: 'cmd+=',
    command: 'view.zoomIn',
    description: 'Zoom in',
    metadata: {
      action: 'Increase the UI zoom level by 10%',
      domain: 'ui_state',
      target: 'zoom_level',
    },
  },
  {
    id: 'view.zoomOut',
    category: KeyCategory.View,
    key: 'cmd+-',
    default: 'cmd+-',
    command: 'view.zoomOut',
    description: 'Zoom out',
    metadata: {
      action: 'Decrease the UI zoom level by 10%',
      domain: 'ui_state',
      target: 'zoom_level',
    },
  },
  {
    id: 'view.zoomReset',
    category: KeyCategory.View,
    key: 'cmd+0',
    default: 'cmd+0',
    command: 'view.zoomReset',
    description: 'Reset zoom',
    metadata: {
      action: 'Reset the UI zoom level to 100%',
      domain: 'ui_state',
      target: 'zoom_level',
    },
  },

  // === Search ===
  {
    id: 'search.focus',
    category: KeyCategory.Search,
    key: 'cmd+f',
    default: 'cmd+f',
    command: 'search.focus',
    description: 'Focus search input',
    when: '!editorFocus',
    metadata: {
      action: 'Focus the global search input field',
      domain: 'ui_state',
      target: 'search_input_focus',
    },
  },
  {
    id: 'search.tqlFocus',
    category: KeyCategory.Search,
    key: 'cmd+shift+f',
    default: 'cmd+shift+f',
    command: 'search.tqlFocus',
    description: 'Focus TQL search',
    metadata: {
      action: 'Focus the TQL (Tag Query Language) search input field',
      domain: 'ui_state',
      target: 'tql_input_focus',
    },
  },

  // === Editing ===
  {
    id: 'editor.save',
    category: KeyCategory.Editing,
    key: 'cmd+s',
    default: 'cmd+s',
    command: 'editor.save',
    description: 'Save current file',
    when: 'isMarkdownEditor',
    priority: 100,
    metadata: {
      action: 'Save changes in the currently active editor',
      domain: 'file_system',
      target: 'active_file_content',
    },
  },

  // === Commands (Key Chords) ===
  {
    id: 'commands.openPalette',
    category: KeyCategory.Custom,
    key: 'cmd+k cmd+p',
    default: 'cmd+k cmd+p',
    command: 'commands.openPalette',
    description: 'Open command palette',
    metadata: {
      action: 'Open the global command palette modal',
      domain: 'ui_state',
      target: 'command_palette_visibility',
    },
  },
  {
    id: 'commands.openSettings',
    category: KeyCategory.Custom,
    key: 'cmd+k cmd+s',
    default: 'cmd+k cmd+s',
    command: 'commands.openSettings',
    description: 'Open settings',
    metadata: {
      action: 'Open the application settings modal',
      domain: 'ui_state',
      target: 'settings_modal_visibility',
    },
  },
  {
    id: 'commands.openKeybindings',
    category: KeyCategory.Custom,
    key: 'cmd+k cmd+k',
    default: 'cmd+k cmd+k',
    command: 'commands.openKeybindings',
    description: 'Open keyboard shortcuts',
    metadata: {
      action: 'Open the keyboard shortcuts reference modal',
      domain: 'ui_state',
      target: 'keybindings_modal_visibility',
    },
  },

  // === Selection ===
  {
    id: 'selection.selectAll',
    category: KeyCategory.Custom,
    key: 'cmd+a',
    default: 'cmd+a',
    command: 'selection.selectAll',
    description: 'Select all files',
    when: 'fileExplorerFocus && !editorFocus',
    metadata: {
      action: 'Select all files in the current view',
      domain: 'ui_state',
      target: 'file_selection',
    },
  },

  // === Tab Management ===
  {
    id: 'tab.new',
    category: KeyCategory.Custom,
    key: 'cmd+t',
    default: 'cmd+t',
    command: 'tab.new',
    description: 'Open new tab',
    metadata: {
      action: 'Create a new tab initialized to the home directory',
      domain: 'ui_state',
      target: 'tab_list',
    },
  },
  {
    id: 'tab.close',
    category: KeyCategory.Custom,
    key: 'cmd+w',
    default: 'cmd+w',
    command: 'tab.close',
    description: 'Close current tab',
    when: '!isFullscreenMode',
    metadata: {
      action: 'Close the currently active workspace tab',
      domain: 'ui_state',
      target: 'tab_list',
    },
  },
  {
    id: 'tab.next',
    category: KeyCategory.Custom,
    key: 'alt+cmd+right',
    default: 'alt+cmd+right',
    command: 'tab.next',
    description: 'Switch to next tab',
    when: '!isFullscreenMode',
    metadata: {
      action: 'Activate the next workspace tab in the list (cyclic)',
      domain: 'ui_state',
      target: 'active_tab',
    },
  },
  {
    id: 'tab.previous',
    category: KeyCategory.Custom,
    key: 'alt+cmd+left',
    default: 'alt+cmd+left',
    command: 'tab.previous',
    description: 'Switch to previous tab',
    when: '!isFullscreenMode',
    metadata: {
      action: 'Activate the previous workspace tab in the list (cyclic)',
      domain: 'ui_state',
      target: 'active_tab',
    },
  },

  // === Window ===
  {
    id: 'window.reload',
    category: KeyCategory.Custom,
    key: 'shift+cmd+r',
    default: 'shift+cmd+r',
    command: 'window.reload',
    description: 'Reload window',
    metadata: {
      action: 'Reload the entire application window',
      domain: 'window',
      target: 'application',
    },
  },

  // === Settings ===
  {
    id: 'settings.openGlobal',
    category: KeyCategory.Custom,
    key: 'cmd+,',
    default: 'cmd+,',
    command: 'settings.openGlobal',
    description: 'Open global settings',
    metadata: {
      action: 'Open the global settings file in the editor',
      domain: 'file_system',
      target: 'settings_file',
    },
  },

  // === Terminal ===
  {
    id: 'terminal.toggle',
    category: KeyCategory.Terminal,
    key: 'ctrl+`',
    default: 'ctrl+`',
    command: 'terminal.toggle',
    description: 'Toggle integrated terminal',
    metadata: {
      action: 'Show or hide the integrated terminal panel',
      domain: 'ui_state',
      target: 'terminal_visibility',
    },
  },
  {
    id: 'terminal.new',
    category: KeyCategory.Terminal,
    key: 'ctrl+shift+`',
    default: 'ctrl+shift+`',
    command: 'terminal.new',
    description: 'Create new terminal',
    metadata: {
      action: 'Open a new terminal tab',
      domain: 'ui_state',
      target: 'terminal_tabs',
    },
  },
  {
    id: 'terminal.focus',
    category: KeyCategory.Terminal,
    key: 'cmd+j',
    default: 'cmd+j',
    command: 'terminal.focus',
    description: 'Focus terminal',
    metadata: {
      action: 'Focus the integrated terminal',
      domain: 'ui_state',
      target: 'terminal_focus',
    },
  },
  {
    id: 'terminal.split',
    category: KeyCategory.Terminal,
    key: 'cmd+/',
    default: 'cmd+/',
    command: 'terminal.split',
    description: 'Split terminal',
    metadata: {
      action: 'Split the terminal panel in Fibonacci pattern',
      domain: 'ui_state',
      target: 'terminal_split',
    },
  },
]
